"""empty message

Revision ID: 94bd9bb88d76
Revises: 80ec4315c133
Create Date: 2024-06-04 18:50:53.348605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bd9bb88d76'
down_revision = '80ec4315c133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('description_content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=9999999),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('description_content',
               existing_type=sa.String(length=9999999),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
